### BEGIN - ESPHome Basic config ###

substitutions:
  
  esp_name: "presence-c4002-test" # Change THIS
  esp_friendly: "Presence C4002 Test" # Change THIS

  dfrobot_name: "DFRobot C4002 Test" # Change THIS
  dfrobot_id: "c4002_test" # Change THIS
  dfrobot_uart: c4002_uart # Change THIS
  dfrobot_topic_prefix: dfrobot-presence # Change THIS

  ipstatic: 10.10.20.163 # Change THIS

esphome:
  name: ${esp_name}
  friendly_name: ${esp_friendly}

esp32:
  board: lolin_s2_mini
  variant: esp32s2
  framework:
    type: esp-idf

logger:
  level: INFO
  baud_rate: 0 #Important. You can't use serial port
#  hardware_uart: UART0
debug:
  update_interval: 30s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  output_power: 15dB
#  reboot_timeout: 10min

# ## Optional - Static IP enable
#   manual_ip: #Change THIS
#     static_ip: ${ipstatic}
#     gateway: 10.10.20.1
#     subnet: 255.255.255.0

## Enable fallback hotspot and captive portal in case wifi connection fails
  ap:
    ssid: ${esp_friendly}
    password: !secret ap_wifi_pass
captive_portal:

## Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
ota:
  - platform: esphome

# ## Web config
# web_server:
#   include_internal: true
#   ota: false

### END - ESPHome Basic config ###

packages:
  esp32_diag: !include .base_esp32diag.yaml
  dfrobot_c4002: !include .base_c4002.yaml